### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by samjett247** [stev-ou/stev-api#4]
Bugs inside our backend programs. 
These should typically be given higher priority for addressing than To-Do or enhancements.

**Comment by samjett247** [comment]
CS department has a space in the uuid (e.g. c s1323 is the uuid) - Should we remove the space? It still works in the api ending, you just add %20 for space. Thoughts? @schuermannator

**Comment by samjett247** [comment]
Instructor and course APIs are not serving content in order of most recent semester. May want to add a sort_df_by_term_code function to sort our df before we start to build the json from it? Just a thought.

**Comment by schuermannator** [comment]
> CS department has a space in the uuid (e.g. c s1323 is the uuid) - Should we remove the space? It still works in the api ending, you just add %20 for space. Thoughts? @schuermannator

I think it’s fine either way. Maybe leave it just for consistency with their data for now?

**Comment by samjett247** [comment]
DSA5970 figure1 API not working

**Comment by samjett247** [comment]
Link to api/v0 not
